---
version: "2"
services:
  config-drive:
    build:
      context: ./config-drive
      dockerfile: Dockerfile
    image: config-drive
    restart: always
    volumes:
      - {/your/cloud-init/data}:/www
    ports:
      - "80:80/tcp"
    hostname: config-drive
  ipxe:
    build:
      context: ./ipxe
      dockerfile: Dockerfile
    image: ipxe
    restart: always
    volumes:
      - {/your/boot-cfg/data}:/srv/tftp
    ports:
      - "69:69/udp"
    hostname: ipxe